//! One freshly derived Tron address per deposit intent, from an account-level xpub.
//!
//! # Why the orchestrator holds only an xpub
//!
//! BIP32 non-hardened derivation needs no private material: `0/i` children of an account xpub are
//! computable from public data alone. So this service can mint a unique receive address per deposit
//! while being unable to spend from any of them. The mnemonic/xprv lives in the isolated signer,
//! which is the only thing that can sweep — same split as `treasury-service` holding the chain mint
//! key while this service holds none.
//!
//! That property is the whole reason a compromise here is survivable: an attacker gets the ability
//! to generate addresses, not to move funds.
//!
//! # Derivation is not something to get subtly wrong
//!
//! A wrong path or a wrong address encoding sends real USDT to addresses whose keys cannot be
//! reconstructed. The BIP32 maths is therefore the `bip32` crate's, not hand-rolled, and the tests
//! below assert against a fixture generated by a completely independent implementation
//! (`@scure/bip32` in JS), not against this code's own output.
//!
//! The fixture was itself validated externally: derived from the canonical public BIP39
//! all-"abandon" test mnemonic, its index-0 address `TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH` is a real
//! Tron mainnet account created 2018-07-12 — which only lines up if the path AND the address
//! encoding are both right.

use bip32::{ChildNumber, XPub};
use sha3::{Digest, Keccak256};

/// BIP44 for Tron is `m/44'/195'/account'/0/index`. The xpub supplied is at the ACCOUNT level
/// (`m/44'/195'/0'`), so this module derives the remaining two non-hardened levels: `0/index`.
///
/// Kept as a constant rather than inlined because "which level is this xpub at" is the single
/// easiest thing to get wrong here, and getting it wrong yields valid-looking addresses that the
/// signer cannot derive keys for.
const CHANGE_LEVEL: u32 = 0;

/// Tron address version byte.
const TRON_ADDRESS_VERSION: u8 = 0x41;

pub struct AddressDeriver {
    account_xpub: XPub,
}

impl AddressDeriver {
    /// `xpub` must be the ACCOUNT-level key, i.e. `m/44'/195'/0'`.
    pub fn from_account_xpub(xpub: &str) -> Result<Self, String> {
        let parsed: XPub = xpub.trim().parse().map_err(|e| format!("invalid account xpub: {e}"))?;
        Ok(Self { account_xpub: parsed })
    }

    /// The receive address for `index`, i.e. `<account>/0/index`.
    ///
    /// Rejects indices in the hardened range: hardened derivation is impossible from a public key,
    /// so accepting one silently would either error deep inside the crate or, worse, wrap into a
    /// different index than the signer will later use to reconstruct the key.
    pub fn address_at(&self, index: u32) -> Result<String, String> {
        if index >= 0x8000_0000 {
            return Err(format!("index {index} is in the hardened range; cannot derive from an xpub"));
        }
        let change = ChildNumber::new(CHANGE_LEVEL, false).map_err(|e| e.to_string())?;
        let idx = ChildNumber::new(index, false).map_err(|e| e.to_string())?;
        let child = self
            .account_xpub
            .derive_child(change)
            .map_err(|e| format!("deriving change level failed: {e}"))?
            .derive_child(idx)
            .map_err(|e| format!("deriving index {index} failed: {e}"))?;
        Ok(tron_address_from_uncompressed(&uncompressed_pubkey(&child)))
    }
}

/// SEC1 uncompressed encoding (65 bytes, `0x04`-prefixed) — Tron hashes this form, not the
/// compressed one.
fn uncompressed_pubkey(xpub: &XPub) -> Vec<u8> {
    xpub.public_key().to_encoded_point(false).as_bytes().to_vec()
}

/// `base58check(0x41 || keccak256(pubkey[1..])[12..32])`.
///
/// The `[1..]` drops the `0x04` SEC1 prefix before hashing and the `[12..32]` takes the low 20
/// bytes — the same derivation as an Ethereum address, then Tron's version byte and checksum.
fn tron_address_from_uncompressed(pubkey: &[u8]) -> String {
    let hash = Keccak256::digest(&pubkey[1..]);
    let mut payload = Vec::with_capacity(21);
    payload.push(TRON_ADDRESS_VERSION);
    payload.extend_from_slice(&hash[12..32]);
    // bs58's `with_check` appends the 4-byte double-SHA256 checksum, which is exactly Tron's.
    bs58::encode(payload).with_check().into_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Account xpub for `m/44'/195'/0'` of the canonical public BIP39 all-"abandon" mnemonic.
    /// A published test vector, never used to hold funds.
    const ACCOUNT_XPUB: &str = "xpub6D1AabNHCupeiLM65ZR9UStMhJ1vCpyV4XbZdyhMZBiJXALQtmn9p42VTQckoHVn8WNqS7dqnJokZHAHcHGoaQgmv8D45oNUKx6DZMNZBCd";

    /// Ground truth from @scure/bip32 — an implementation with no shared code with ours. Index 0 is
    /// additionally a real Tron mainnet account created 2018-07-12, so these are not merely
    /// self-consistent.
    const EXPECTED: [(u32, &str); 5] = [
        (0, "TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH"),
        (1, "TSeJkUh4Qv67VNFwY8LaAxERygNdy6NQZK"),
        (2, "TYJPRrdB5APNeRs4R7fYZSwW3TcrTKw2gx"),
        (3, "TRhVWK5XEDkQBDevcdCWW7RW51aRncty4W"),
        (4, "TT2X2yyubp7qpAWYYNE5JQWBtoZ7ikQFsY"),
    ];

    #[test]
    fn derives_the_independently_generated_addresses() {
        let d = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).expect("fixture xpub must parse");
        for (index, want) in EXPECTED {
            assert_eq!(d.address_at(index).unwrap(), want, "address at index {index}");
        }
    }

    /// Every index must give a DIFFERENT address. A deriver that ignored the index would still
    /// pass a single-address test while sending every depositor to the same place.
    #[test]
    fn each_index_yields_a_distinct_address() {
        let d = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).unwrap();
        let addrs: Vec<String> = (0..25).map(|i| d.address_at(i).unwrap()).collect();
        let mut uniq = addrs.clone();
        uniq.sort();
        uniq.dedup();
        assert_eq!(uniq.len(), addrs.len(), "derived addresses must be unique per index");
    }

    /// Derivation must be a pure function of (xpub, index) — the sweep signer reconstructs the key
    /// from the index alone, so a non-deterministic address is unrecoverable funds.
    #[test]
    fn derivation_is_deterministic() {
        let a = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).unwrap();
        let b = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).unwrap();
        for i in [0u32, 7, 100, 65_535, 1_000_000] {
            assert_eq!(a.address_at(i).unwrap(), b.address_at(i).unwrap());
        }
    }

    #[test]
    fn every_derived_address_is_valid_base58check_with_the_tron_version_byte() {
        let d = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).unwrap();
        for i in [0u32, 1, 999, 123_456] {
            let addr = d.address_at(i).unwrap();
            let bytes = bs58::decode(&addr)
                .with_check(Some(TRON_ADDRESS_VERSION))
                .into_vec()
                .unwrap_or_else(|e| panic!("index {i} produced {addr}, which failed base58check: {e}"));
            assert_eq!(bytes.len(), 21, "version byte + 20 address bytes");
            assert!(addr.starts_with('T'), "Tron mainnet-format addresses start with T, got {addr}");
        }
    }

    /// Hardened indices cannot be derived from public material. Refuse rather than let the crate
    /// wrap or error obscurely — the signer would otherwise reconstruct a different key.
    #[test]
    fn hardened_index_is_refused() {
        let d = AddressDeriver::from_account_xpub(ACCOUNT_XPUB).unwrap();
        let err = d.address_at(0x8000_0000).expect_err("hardened must be refused");
        assert!(err.contains("hardened"), "error should name the cause, got: {err}");
    }

    #[test]
    fn garbage_xpub_is_refused() {
        for bad in ["", "not-an-xpub", "xpub-truncated", ACCOUNT_XPUB.trim_end_matches('d')] {
            assert!(
                AddressDeriver::from_account_xpub(bad).is_err(),
                "must reject {bad:?} rather than derive from nonsense"
            );
        }
    }
}
